services:
  jupyter:
    build:
      dockerfile: Dockerfile
      context: .
    image: jupyter
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./config:/home/jovyan/.jupyter
    working_dir: /home/jovyan/notebooks
    restart: always